CREATE database customer_behaviour_analysis;

show databases;
use customer_behaviour_analysis;
show tables;


select * from customer;
-- 1. what is the total revenue generated by male vs female customer

select gender, sum(purchase_amount) as revenue from customer
group by gender;

-- 2) which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer
where discount_applied="Yes" and purchase_amount>=(select avg(purchase_amount) from customer);

-- 3)which are the top 5 products with highest average review rating;
select item_purchased, round(Avg(review_rating),2) as Average_review_rating from customer
group by item_purchased
order by Average_review_rating desc
limit 5;

-- 4) Compare the average purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount) as purchase_amount from customer
where shipping_type in ("Standard","Express")
group by shipping_type;

-- 5) do subscriber customer spend more? Compre average spend & total revenue between subscribers and non-subscriber

select subscription_status, count(customer_id) as total_customer, round(avg(purchase_amount),2) as average_spend, sum(purchase_amount) as total_revenue 
from customer 
group by subscription_status
order by total_revenue,average_spend desc;


select * from customer;

-- 6) which 5 product have the highest percentage of purchase with discounts applied?
select item_purchased,
round(sum(Case when discount_applied="Yes" Then 1 else 0 end)/count(*)*100,2) as discount_rate from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 7) segment  customers into new, returning, loyal based on their total numbers of previous purchases, and show the count of each segment
-- CTE
with customer_type as (
select customer_id, previous_purchases, 
Case 
	when previous_purchases =1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "loyal"
    end as customer_segment
from customer
)
select customer_segment, count(*) as number_of_customers from customer_type
group by customer_segment;
    
select * from customer;

-- 8) what are the top 3 most purchased products within each category
WITH item_counts as(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank, category, item_purchased, total_orders from item_counts
where item_rank<=3;

-- 9) are customers who are rrepeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases>5
group by subscription_status;

-- 10) what is the revenue contribution of each age group?
select sum(purchase_amount) as revenue, age_group from customer
group by age_group 
order by revenue desc;
select * from customer;

    